import test from 'node:test';import assert from 'node:assert/strict';
import {DashboardState,validateProjection,views,taskLabel,publicationLabel,freshness} from '../web/dashboard-model.mjs';import {demoProjection} from '../web/dashboard-demo.mjs';
test('Task mapping does not turn creative/lifecycle into task statuses',()=>{assert.equal(taskLabel('preparing'),'V PRÍPRAVE');assert.equal(taskLabel('running'),'PREBIEHA');assert.equal(taskLabel('to-do'),'NEZAČATÉ');assert.equal(taskLabel('APPROVED'),'UNCERTAIN');assert.equal(taskLabel('ACTIVE'),'UNCERTAIN');});
test('NOW and next steps reference the same items, sorted by evidence priority',()=>{const v=views(demoProjection());assert.strictEqual(v.now,v.next);assert.equal(v.now[0].fields.priority,'P0');assert.equal(v.relevantOffers[0].id,'demo:service');});
test('Approval and reported publication never imply platform verification',()=>{const i=demoProjection().items.find(i=>i.id==='demo:reported');assert.equal(publicationLabel(i),'Publikovanie oznámené · platformovo neoverené');i.fields.platform_verification='PLATFORM_VERIFIED';assert.equal(publicationLabel(i),'Publikovanie oznámené · platformovo neoverené');i.links=[{role:'publication',url:'https://example.invalid/post'}];assert.equal(publicationLabel(i),'Publikované · platformovo overené');i.fields.publication='NOT_PUBLISHED';assert.equal(publicationLabel(i),'NOT_PUBLISHED');});
test('Failure preserves last snapshot, invalid dates stay unknown and stale',()=>{const s=new DashboardState();s.accept(demoProjection());const before=s.data;s.fail('error');assert.strictEqual(s.data,before);assert.equal(freshness({last_success_at:'bad'}).label,'Bez úspešného čítania');assert.equal(freshness({status:'error',last_success_at:new Date().toISOString()}).stale,true);});
test('Logout clears all business data, and late responses cannot restore it',()=>{const s=new DashboardState();s.accept(demoProjection());const epoch=s.epoch;s.clear();assert.equal(s.data,null);assert.equal(s.accept(demoProjection(),epoch),false);assert.equal(s.data,null);});
test('Contract rejects duplicate IDs and missing provenance without dropping conflicts',()=>{const d=demoProjection();assert.equal(validateProjection(d).items.find(i=>i.id==='demo:campaign').conflicts.length,1);d.items.push(d.items[0]);assert.throws(()=>validateProjection(d));});

test('Idea metrics count evidence only and flag partial source coverage',async()=>{const {metrics}=await import('../web/dashboard-model.mjs');const d=demoProjection();d.items.find(i=>i.kind==='idea').fields.approval='APPROVED';const m=metrics(d);assert.equal(m.ideas,1);assert.deepEqual(m.stages,[['PROPOSED',1]]);assert.equal(m.partial,true);assert.equal(m.tasks,2);assert.equal(m.campaigns,1);assert.equal(metrics({items:[],sources:[]}).ideas,0);});

test('Service ideas join idea metrics while NOW stays separate and ACTIVE is not availability',async()=>{const {metrics}=await import('../web/dashboard-model.mjs');const d=demoProjection(),base=d.items.find(i=>i.kind==='service');d.items.push({...structuredClone(base),id:'synthetic:active',fields:{lifecycle:'ACTIVE',availability:'TBD'}},{...structuredClone(base),id:'synthetic:idea',fields:{lifecycle:'IDEA'}});const v=views(d);assert.equal(v.activeServices.length,1);assert.equal(v.activeServices[0].fields.availability,'TBD');assert.equal(v.serviceIdeas.length,1);assert.equal(v.ideas.length,2);assert(v.ideas.every(i=>i.kind!=='task'));assert.equal(metrics(d).ideas,2);assert.deepEqual(metrics(d).stages,[['IDEA',1],['PROPOSED',1]]);});
