import test from 'node:test';import assert from 'node:assert/strict';
import {DashboardState,validateProjection,views,taskLabel,publicationLabel,freshness} from '../web/dashboard-model.mjs';import {demoProjection} from '../web/dashboard-demo.mjs';
test('Task mapping does not turn creative/lifecycle into task statuses',()=>{assert.equal(taskLabel('preparing'),'V PRÍPRAVE');assert.equal(taskLabel('running'),'PREBIEHA');assert.equal(taskLabel('to-do'),'NEZAČATÉ');assert.equal(taskLabel('APPROVED'),'UNCERTAIN');assert.equal(taskLabel('ACTIVE'),'UNCERTAIN');});
test('NEXT selects bounded actionable steps from NOW',()=>{const v=views(demoProjection());assert.notStrictEqual(v.now,v.next);assert.ok(v.next.length<=5);assert.equal(v.now[0].fields.priority,'P0');assert.equal(v.relevantOffers[0].id,'demo:service');});
test('Approval and reported publication never imply platform verification',()=>{const i=demoProjection().items.find(i=>i.id==='demo:reported');assert.equal(publicationLabel(i),'Publikovanie oznámené · platformovo neoverené');i.fields.platform_verification='PLATFORM_VERIFIED';assert.equal(publicationLabel(i),'Publikovanie oznámené · platformovo neoverené');i.links=[{role:'publication',url:'https://example.invalid/post'}];assert.equal(publicationLabel(i),'Publikované · platformovo overené');i.fields.publication='NOT_PUBLISHED';assert.equal(publicationLabel(i),'NOT_PUBLISHED');});
test('Failure preserves last snapshot, invalid dates stay unknown and stale',()=>{const s=new DashboardState();s.accept(demoProjection());const before=s.data;s.fail('error');assert.strictEqual(s.data,before);assert.equal(freshness({last_success_at:'bad'}).label,'Bez úspešného čítania');assert.equal(freshness({status:'error',last_success_at:new Date().toISOString()}).stale,true);});
test('Logout clears all business data, and late responses cannot restore it',()=>{const s=new DashboardState();s.accept(demoProjection());const epoch=s.epoch;s.clear();assert.equal(s.data,null);assert.equal(s.accept(demoProjection(),epoch),false);assert.equal(s.data,null);});
test('Contract rejects duplicate IDs and missing provenance without dropping conflicts',()=>{const d=demoProjection();assert.equal(validateProjection(d).items.find(i=>i.id==='demo:campaign').conflicts.length,1);d.items.push(d.items[0]);assert.throws(()=>validateProjection(d));});

test('Idea metrics count evidence only and flag partial source coverage',async()=>{const {metrics}=await import('../web/dashboard-model.mjs');const d=demoProjection();d.items.find(i=>i.kind==='idea').fields.approval='APPROVED';const m=metrics(d);assert.equal(m.ideas,1);assert.deepEqual(m.stages,[['PROPOSED',1]]);assert.equal(m.partial,true);assert.equal(m.tasks,2);assert.equal(m.campaigns,1);assert.equal(metrics({items:[],sources:[]}).ideas,0);});

test('Service ideas join idea metrics while NOW stays separate and ACTIVE is not availability',async()=>{const {metrics}=await import('../web/dashboard-model.mjs');const d=demoProjection(),base=d.items.find(i=>i.kind==='service');d.items.push({...structuredClone(base),id:'synthetic:active',fields:{lifecycle:'ACTIVE',availability:'TBD'}},{...structuredClone(base),id:'synthetic:idea',fields:{lifecycle:'IDEA'}});const v=views(d);assert.equal(v.activeServices.length,1);assert.equal(v.activeServices[0].fields.availability,'TBD');assert.equal(v.serviceIdeas.length,1);assert.equal(v.ideas.length,2);assert(v.ideas.every(i=>i.kind!=='task'));assert.equal(metrics(d).ideas,2);assert.deepEqual(metrics(d).stages,[['IDEA',1],['PROPOSED',1]]);});

test('22 NOW records remain distinct from at most five NEXT steps',()=>{const d=demoProjection(),base=d.items.find(i=>i.kind==='task');d.items=Array.from({length:22},(_,n)=>({...structuredClone(base),id:'task:'+n,fields:{...base.fields,priority:'P1',next_step:'Overiť konkrétny krok',task_status:'NEZAČATÉ'}}));const v=views(d);assert.equal(v.now.length,22);assert.equal(v.next.length,5);assert.notStrictEqual(v.next,v.now);});
test('missing supplier is a data gap, never an inferred business decision',()=>{const d=demoProjection(),base=d.items[0];d.items=[{...base,id:'gap',kind:'decision',fields:{open_questions:'Dodávateľ MISSING'}},{...base,id:'decision',kind:'decision',fields:{decision_type:'business',summary:'Potvrdiť GO/NO-GO'}}];assert.equal(views(d).decisions.length,1);assert.equal(views(d).dataGaps.length,1);});
test('legacy Drive Markdown remains stale despite a recent read',()=>{assert.equal(freshness({provider:'drive',role:'markdown',status:'ok',last_success_at:new Date().toISOString()}).stale,true);});

test('same stable service ID is one entity with conflicting evidence retained',()=>{const d=demoProjection(),s=structuredClone(d.items.find(i=>i.kind==='service'));s.id='LF-SVC-031';s.fields.lifecycle='IDEA';d.items=[s,{...structuredClone(s),fields:{...s.fields,availability:'Nie'}}];const checked=validateProjection(d);assert.equal(checked.items.length,1);assert.equal(views(checked).serviceIdeas.length,1);assert.ok(checked.items[0].conflicts.length);});
test('missing GitHub brief produces a campaign coverage warning',async()=>{const {campaignCoverage}=await import('../web/dashboard-model.mjs');assert.ok(campaignCoverage(demoProjection()).missing.length);});
test('unavailable GitHub never becomes current after recalculation',()=>{const d=demoProjection();const s={...d.sources[0],provider:'github',role:'brief',status:'error',last_success_at:new Date().toISOString()};assert.equal(freshness(s).stale,true);});
