import test from 'node:test';import assert from 'node:assert/strict';
import {statusTone,campaignGroup,dataStatus,evidenceFor,postDisplay,recentAdditions} from '../web/reporting.mjs';
import {discoverBriefPaths,parseBrief,ingestBriefs} from '../scripts/lib/campaign-ingestion.mjs';
import {demoProjection} from '../web/dashboard-demo.mjs';
const path='MD campaigns/LF_CAMPAIGN_SYNTHETIC/LF_CAMPAIGN_SYNTHETIC_BRIEF.md';
const doc={path,revision:'synthetic-revision',read_at:'2026-10-08T00:00:00Z',content:'# Synthetic campaign\n## CAMPAIGN NAME / STATUS\n- Business Campaign ID: **LF-CAM-SYNTHETIC**\n- Campaign name: **Synthetic campaign**\n- Campaign lifecycle: **PREPARING**\n## 2. OBJECTIVE / AUDIENCE / OFFER\nIncrease synthetic attendance.\n## PENDING ACTIONS\n- Confirm synthetic launch.\n## ASSET / FILE EVIDENCE\nhttps://drive.google.com/drive/folders/synthetic\nhttps://drive.google.com/file/d/synthetic/view'};
test('status colors are semantic and lifecycle display grouping preserves raw fields',()=>{for(const [status,tone]of [['RUNNING','success'],['ACTIVE','success'],['READY','info'],['PREPARING','warning'],['DRAFT','danger'],['P0','danger'],['P1','warning']])assert.equal(statusTone(status),tone);const i={fields:{lifecycle:'PLANNED'},conflicts:[]};assert.equal(campaignGroup(i),'PREPARING');assert.equal(i.fields.lifecycle,'PLANNED');i.conflicts=[{field:'lifecycle'}];assert.equal(campaignGroup(i),'REVIEW');});
test('legacy pseudo coverage is excluded from source count, real errors are named',()=>{const d=demoProjection();d.sources.push({id:'coverage:campaign-details',role:'coverage',title:'Legacy coverage',status:'missing'});const status=dataStatus(d);assert.equal(status.total,2);assert.equal(status.missing[0].title,'DEMO · nedostupný zdroj');assert.equal(status.legacyCoverage,true);});
test('discovery checks canonical folder/file pattern and refuses truncated trees',()=>{assert.deepEqual(discoverBriefPaths({tree:[{path,type:'blob'},{path:'archive/'+path,type:'blob'},{path:'MD campaigns/LF_CAMPAIGN_A/LF_CAMPAIGN_B_BRIEF.md',type:'blob'}]}),[path]);assert.throws(()=>discoverBriefPaths({truncated:true,tree:[]}));});
test('brief ingestion handles bold bullet metadata and numbered sections',()=>{const {item}=parseBrief(doc);assert.equal(item.id,'LF-CAM-SYNTHETIC');assert.equal(item.fields.lifecycle,'PREPARING');assert.match(item.fields.objective,/synthetic attendance/);assert.match(item.fields.next_step,/Confirm/);assert.equal(item.links.filter(l=>l.role==='asset_folder').length,1);});
test('exact ID join retains register disagreement and never infers approval',()=>{const d=demoProjection(),c=d.items.find(i=>i.kind==='campaign');c.id='LF-CAM-SYNTHETIC';c.fields.lifecycle='RUNNING';d.sources.push({id:'coverage:campaign-details',role:'coverage',title:'Legacy',status:'missing'});const enriched=ingestBriefs(d,[doc],{revision:doc.revision,read_at:doc.read_at});const merged=enriched.items.filter(i=>i.id===c.id);assert.equal(merged.length,1);assert.equal(merged[0].fields.registry_lifecycle,'RUNNING');assert.ok(merged[0].conflicts.some(c=>c.field==='lifecycle'));assert.equal(merged[0].fields.approval,'TBD');assert(!enriched.sources.some(s=>s.id==='coverage:campaign-details'));assert.deepEqual(d.items.find(i=>i.id===c.id).fields.lifecycle,'RUNNING');});
test('unmapped campaign has per-entity missing brief, API failure is a real source error',()=>{const d=demoProjection();const enriched=ingestBriefs(d,[doc],{revision:doc.revision,read_at:doc.read_at});assert.equal(enriched.items.find(i=>i.id==='demo:campaign').fields.brief_availability,'NO');const failed=ingestBriefs(enriched,[],{revision:doc.revision,error:'Unavailable'});assert.equal(failed.sources.find(s=>s.id==='github:campaign-discovery').status,'error');assert.equal(failed.items.find(i=>i.id==='LF-CAM-SYNTHETIC').fields.brief_availability,'UNAVAILABLE');assert.equal(failed.sources.find(s=>s.role==='brief').last_success_at,doc.read_at);});
test('FB evidence follows explicit IDs and cannot treat folder as poster',()=>{const d=demoProjection(),c=d.items.find(i=>i.kind==='campaign'),o=d.items.find(i=>i.kind==='output');c.links=[{role:'brief',url:'https://github.com/wwwsusi/lady-fitness-core/blob/main/synthetic.md'},{role:'asset_folder',url:'https://drive.google.com/drive/folders/synthetic'}];assert.ok(evidenceFor(o,d).brief);assert.equal(evidenceFor(o,d).asset,null);o.fields.approval='APPROVED';assert.equal(postDisplay(o,d).status,'DRAFT');});
test('services ACTIVE does not affect availability and additions require no fabricated dates',()=>{const d=demoProjection(),s=d.items.find(i=>i.kind==='service');s.fields.lifecycle='ACTIVE';s.fields.availability='Nie';assert.equal(recentAdditions(d).length,0);assert.equal(s.fields.availability,'Nie');s.fields.lifecycle='IDEA';assert.equal(recentAdditions(d)[0].id,s.id);assert.equal(s.fields.added_at,undefined);});

test('repeated enrichment preserves Sheet register provenance and disagreement',()=>{const d=demoProjection(),c=d.items.find(i=>i.kind==='campaign');c.id='LF-CAM-SYNTHETIC';c.fields.lifecycle='RUNNING';const once=ingestBriefs(d,[doc],{revision:doc.revision,read_at:doc.read_at});const twice=ingestBriefs(once,[doc],{revision:doc.revision,read_at:doc.read_at});const campaigns=twice.items.filter(i=>i.id===c.id);assert.equal(campaigns.length,1);assert.equal(campaigns[0].fields.registry_lifecycle,'RUNNING');assert.equal(campaigns[0].provenance.field_sources.registry_lifecycle,c.source_id);assert.ok(campaigns[0].conflicts.some(i=>i.field==='lifecycle'));});
