import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {SECTIONS,DashboardState} from '../web/dashboard-model.mjs';
import {uxProjection,campaignBuckets,taskGroup,calendarEvents,pragueToday,addDays,monthGrid,moveMonth,qualitySummary,availableColumns,loadPreferences,savePreferences,reorderColumn,toggleColumn,visibleColumns,textPreview,preferenceKey} from '../web/ux-model.mjs';
import {renderUX,renderLongText} from '../web/ux.mjs';
import {fixture,item} from './fixtures/ux-v2.mjs';
class Node{
 constructor(tag,text){this.tagName=tag.toUpperCase();this._text=text??'';this.children=[];this.attrs={};this.dataset={};this.style={};}
 get textContent(){return String(this._text)+this.children.map(n=>n.textContent).join(' ');}
 set textContent(value){this._text=value;this.children=[];}
 append(...nodes){this.children.push(...nodes);}
 replaceChildren(...nodes){this._text='';this.children=nodes;}
 setAttribute(k,v){this.attrs[k]=String(v);}
 getAttribute(k){return this.attrs[k];}
 querySelectorAll(selector){const match=n=>selector==='[aria-label]'?n.attrs['aria-label']!==undefined:n.tagName===selector.toUpperCase();return this.children.flatMap(n=>[...(match(n)?[n]:[]),...n.querySelectorAll(selector)]);}
 querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
 focus(){this.focused=true;}
}
function harness(section,data=fixture(),extra={}){const parent=new Node('main'),tables=[],opened=[],months=[];const make=(tag,text,target,cls)=>{const n=new Node(tag,text);n.className=cls||'';target?.append(n);return n;},action=(label,fn,target)=>{const b=make('button',label,target);b.type='button';b.onclick=fn;return b;},tableShell=(title,columns,target,note,controls)=>{tables.push({title,columns,controls});const box=make('section',title,target),table=make('table',null,box),body=make('tbody',null,table);return {box,body};};renderUX({data,section,parent,make,action,tableShell,detail:i=>opened.push(i.id),statusBadge:(v,target)=>make('span',v,target),calendarMonth:'2026-10',onCalendarMonth:m=>months.push(m),storage:null,...extra});return {parent,tables,opened,months,make};}
test('navigation has Úlohy and Kalendár, with no NOW or Management label',()=>{assert(SECTIONS.some(([key,label])=>key==='tasks'&&label==='Úlohy'));assert(SECTIONS.some(([key])=>key==='calendar'));assert(!SECTIONS.some(([,label])=>['NOW','Management'].includes(label)));});
test('overview canonical summary, campaign counts and real severities',()=>{const v=uxProjection(fixture(),'2026-10-10');assert.deepEqual(v.counts,[['Úlohy',7],['Kampane',2],['Služby',1],['Produkty',1]]);assert.deepEqual(v.campaigns.groups.map(g=>g.items.length),[1,0,0,1,0]);assert.deepEqual(v.quality,[['WARN',2]]);const ui=harness('overview');assert(!ui.parent.textContent.includes('NEXT STEPS'));assert(!ui.parent.textContent.includes('Register Supabase'));assert(ui.parent.textContent.includes('Other / Unclassified'));});
test('open canonical tasks only; inclusive five calendar days; NULL and terminal excluded',()=>{const v=uxProjection(fixture(),'2026-10-10');assert.deepEqual(v.dueSoon.map(i=>i.id),['t1','t2']);assert.deepEqual(v.overdue.map(i=>i.id),['t3']);assert.deepEqual(v.launches.map(e=>e.item.id),['c1','s1']);});
test('Prague business today and date-only arithmetic survive UTC/DST boundaries',()=>{assert.equal(pragueToday(new Date('2026-10-09T22:30:00Z')),'2026-10-10');assert.equal(pragueToday(new Date('2026-12-31T23:30:00Z')),'2027-01-01');assert.equal(addDays('2026-10-24',5),'2026-10-29');assert.equal(addDays('2026-02-30',1),null);});
test('month grid is Monday-first, includes today and changes across year',()=>{const cells=monthGrid('2026-10','2026-10-10');assert.equal(cells.length,42);assert.equal(cells[0].date,'2026-09-28');assert.equal(cells.filter(c=>c.today).length,1);assert.equal(moveMonth('2026-12',1),'2027-01');assert.equal(moveMonth('2026-01',-1),'2025-12');});
test('canonical event placement uses only task due or entity launch; no duration or fabricated dates',()=>{const events=calendarEvents(fixture());const campaign=events.filter(e=>e.item.kind==='campaign');assert.deepEqual(campaign.map(e=>[e.item.id,e.type,e.date]),[['c1','launch','2026-10-10']]);assert(!events.some(e=>e.item.id==='p1'));assert(!events.some(e=>e.date==='2026-10-20'||e.date==='2026-10-21'));assert(campaign.every(e=>!Object.hasOwn(e,'end')));});
test('known categories project safely; unknown and blocked tasks stay visible',()=>{const data=fixture(),v=uxProjection(data,'2026-10-10');assert.equal(taskGroup(data.items[0]),'campaigns');assert.equal(taskGroup(data.items[1]),'brand');assert.equal(taskGroup(data.items[2]),'staff');assert.equal(taskGroup(data.items[4]),'other');assert.equal(v.important.flatMap(g=>g.items).length,5);assert(v.important.find(g=>g.id==='other').items.some(i=>i.id==='t5'));});
test('campaign order and actual registry codes; missing bucket stays unavailable',()=>{const data=fixture(),groups=campaignBuckets(data).groups;assert.deepEqual(groups.map(g=>g.id),['published','review','preparing','draft','completed']);assert(!data.status_catalog.definitions.some(d=>d.code==='RUNNING'));data.status_catalog.definitions=data.status_catalog.definitions.filter(d=>d.code!=='IN_REVIEW');assert.equal(campaignBuckets(data).groups[1].available,false);const ui=harness('campaigns',data);const headings=ui.parent.querySelectorAll('h3').map(n=>n.textContent);assert.deepEqual(headings.slice(5),['Beží teraz / Published','In Review','V príprave','Draft / Idea','Dokončené']);assert(ui.parent.textContent.includes('Nedostupné'));ui.parent.querySelectorAll('button').find(n=>n.textContent==='Synthetic c1').onclick();assert.deepEqual(ui.opened,['c1']);});
test('task table compact order, long next_step full accessible native disclosure, no source mutation',()=>{const data=fixture(),before=structuredClone(data),ui=harness('tasks',data);assert.deepEqual(ui.tables[0].columns,['Priorita','Úloha','Stav','Ďalší krok','Owner','Kategória']);assert.equal(ui.tables[0].controls,false);const details=ui.parent.querySelector('details');assert(details.querySelector('summary'));assert.equal(details.querySelector('p').textContent,'n'.repeat(200));assert.deepEqual(data,before);assert.equal(textPreview('short').long,false);});
test('real severity only, unavailable OK count and issue-only coverage',()=>{assert.deepEqual(qualitySummary({issues:[{severity:'ERROR'},{severity:'WARN'}]}),[['ERROR',1],['WARN',1]]);assert.deepEqual(qualitySummary({issues:[]}),[]);assert.deepEqual(qualitySummary(undefined),[]);});
test('shared default columns, visibility and order persistence, required title',()=>{const columns=availableColumns(fixture().items.filter(i=>i.kind==='service')),memory=new Map(),storage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)};let prefs=loadPreferences(storage,'offers',columns);assert.deepEqual(visibleColumns(prefs,columns).map(c=>c.id),['name','lifecycle','availability','price','owner']);prefs=toggleColumn(prefs,'owner',false,columns);prefs=reorderColumn(prefs,'price',-1);assert(savePreferences(storage,'offers',prefs));assert.deepEqual(loadPreferences(storage,'offers',columns),prefs);assert(!loadPreferences(storage,'products',columns).visible.includes('proposed'));assert(toggleColumn(prefs,'name',false,columns).visible.includes('name'));assert(memory.has(preferenceKey('offers')));});
test('corrupt or unavailable localStorage safely falls back',()=>{const columns=availableColumns(fixture().items.filter(i=>i.kind==='product')),defaults=loadPreferences(null,'products',columns);assert.deepEqual(loadPreferences({getItem:()=>'{oops'},'products',columns),defaults);assert.deepEqual(loadPreferences({getItem(){throw Error('blocked');}},'products',columns),defaults);assert.equal(savePreferences({setItem(){throw Error('blocked');}},'products',defaults),false);assert.equal(savePreferences(null,'products',defaults),false);});
test('rendered column controls use semantic buttons and persist user changes',()=>{const memory=new Map(),storage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)},ui=harness('offers',fixture(),{storage});const owner=ui.parent.querySelectorAll('input').find(n=>n.getAttribute('aria-label')==='Zobraziť Owner');owner.checked=false;owner.onchange();assert(!JSON.parse(memory.get(preferenceKey('offers'))).visible.includes('owner'));const button=ui.parent.querySelectorAll('button').find(n=>n.getAttribute('aria-label')==='Posunúť doľava · Cena');assert.equal(button.type,'button');button.onclick();assert(JSON.parse(memory.get(preferenceKey('offers'))).order.indexOf('price')<3);assert(harness('products').parent.textContent.includes('browser storage'));});
test('calendar renders 42 cells, today, canonical events, extra disclosure and detail reuse',()=>{const data=fixture();data.items.push(item('extra1','task',{task_status:'IN_PROGRESS',due_date:'2026-10-10'}),item('extra2','task',{task_status:'IN_PROGRESS',due_date:'2026-10-10'}));const ui=harness('calendar',data);assert.equal(ui.parent.querySelectorAll('td').length,42);assert.equal(ui.parent.querySelectorAll('th').length,7);assert(ui.parent.querySelectorAll('details').some(n=>n.textContent.includes('ďalších')));ui.parent.querySelectorAll('button').find(n=>n.textContent==='Nasledujúci mesiac →').onclick();assert.deepEqual(ui.months,['2026-11']);ui.parent.querySelectorAll('button').find(n=>n.textContent.includes('Synthetic c1')).onclick();assert.deepEqual(ui.opened,['c1']);});
test('header reload uses existing callback, logout remains server POST, labels and theme preserved',()=>{const html=fs.readFileSync(new URL('../web/index.html',import.meta.url),'utf8'),app=fs.readFileSync(new URL('../web/app.mjs',import.meta.url),'utf8'),dashboard=fs.readFileSync(new URL('../web/dashboard.mjs',import.meta.url),'utf8');assert(html.includes('Reload Data'));assert(html.includes('Connect to DB'));assert(html.includes('Logout'));assert.equal((html.match(/id="disconnect"/g)||[]).length,1);assert(html.indexOf('id="disconnect"')<html.indexOf('</header>'));assert(dashboard.includes('await refreshLive()'));assert(app.includes("fetch(endpoint+'/api/logout',{method:'POST',credentials:'include'}"));assert(app.includes("themeButton.onclick"));assert(app.includes("await liveReport({restore:true})"));assert(!app.includes("'/api/report'"));});
test('existing validation rejects bad DTO; failed refresh retains good canonical data',()=>{const state=new DashboardState();state.accept(fixture());const before=structuredClone(state.data);state.fail('failed reload');assert.deepEqual(state.data,before);assert.equal(state.error,'failed reload');assert.throws(()=>state.accept({...fixture(),schema_version:99}));});
