import {mergeLiveReport} from './live-report.mjs?v=20261008-manual-v7';
import {SECTIONS,DashboardState,views,freshness,publicationLabel,taskLabel,dateValue,metrics,campaignCoverage,ideaBucket} from './dashboard-model.mjs?v=20261008-manual-v7';
import {statusTone,campaignGroup,dataStatus,evidenceFor,postDisplay,taskCategory,groupTasksByCategory,latestNowItems,nowAddedDate,itemTitle} from './reporting.mjs?v=20261008-manual-v7';
import {snapshotAge} from './snapshot.mjs';
import {demoProjection} from './dashboard-demo.mjs';
import {safeUrl,searchText} from './model.mjs';
const make=(tag,text,parent,className)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(className)n.className=className;parent?.append(n);return n;};
const action=(text,fn,parent)=>{const n=make('button',text,parent);n.type='button';n.onclick=fn;return n;};
const labels={category:'Kategória',area:'Oblasť (historická)',type:'Typ služby',approval_evidence:'Dôkaz schválenia (zdroj / dátum / verzia)',registry_lifecycle:'Lifecycle podľa registra',registry_approval:'Schválenie podľa registra',registry_publication:'Publikovanie podľa registra',role:'Rola assetu',file_id:'Drive file ID',version:'Verzia',priority:'Priorita',task_status:'Úloha',next_step:'Ďalší krok',owner:'Zodpovednosť',due:'Termín / kontext',added_at:'Dátum pridania',lifecycle:'Lifecycle',placement:'Umiestnenie',objective:'Cieľ',start:'Začiatok',end:'Koniec',creative:'Kreatíva',approval:'Schválenie',publication:'Publikovanie',platform_verification:'Platformová evidencia',channel:'Kanál',publish_at:'Publikačný termín',availability:'Dostupnosť',audience:'Publikum / cenová skupina',creation_audience:'Publikum tvorby',value:'Hodnota pre publikum',included:'Zahrnuté',booking:'Booking / CTA',capacity:'Kapacita',units:'Počet jednotiek',unit:'Jednotka',unit_price:'Cena / jednotka',price:'Aktuálna cena',proposed_price:'Navrhovaná nová cena',price_effective:'Účinnosť ceny',evidence_status:'Stav evidencie',summary:'Stručný obsah',open_questions:'Otvorené otázky',blocking:'Blokuje ďalšiu prácu',date:'Dátum',results:'Výsledky',pending:'Lokálne pending actions'};
export function createDashboard({focusMap,refreshLive}){
 const state=new DashboardState(),nav=document.getElementById('dashboard-nav'),root=document.getElementById('dashboard'),map=document.getElementById('map-workspace'),panel=document.getElementById('dashboard-detail');
 let section='overview',query='',filter='',importRecord=null,savedSnapshot=null,recalculatedAt=null,fieldFilters={},liveConnected=false;
 const stamp=value=>dateValue(value)===null?'TBD':new Date(value).toLocaleString('sk-SK',{timeZone:'Europe/Prague'});
 function navigate(next){section=next;query='';filter='';fieldFilters={};panel.close();render();}
 for(const [key,label]of SECTIONS){const b=action(label,()=>navigate(key),nav);b.dataset.section=key;}
 function sourceFor(item){return state.data?.sources.find(s=>s.id===item.source_id);}
 function canonical(item,parent){const s=sourceFor(item),url=safeUrl(s?.url);if(url){const a=make('a','Canonical zdroj ↗',parent);a.href=url;a.target='_blank';a.rel='noopener noreferrer';}}
 function itemCard(item,parent){
  const card=make('article',null,parent,'dash-card');const top=make('div',null,card,'card-meta');
  const badge=item.kind==='task'?item.fields.priority||'TBD':item.fields.evidence_status||item.fields.lifecycle||item.fields.creative||'TBD';statusBadge(badge,top);card.dataset.tone=statusTone(badge);
  if(item.conflicts.length)make('span','Konflikt zdrojov',top,'conflict-label');
  action(itemTitle(item),()=>detail(item),card).className='card-title';
  const f=item.fields;
  if(item.kind==='task'){statusBadge(taskLabel(f.task_status),card);make('small','Vlastník: '+(f.owner||'TBD'),card);make('p',f.next_step||'Ďalší krok: TBD',card);}
  else if(item.kind==='output'){make('p',`${f.creative||'TBD'} · approval: ${f.approval||'TBD'}`,card);make('p',publicationLabel(item),card);make('small','Publikačný termín: '+(f.publish_at||'TBD'),card);}
  else if(['product','service','idea'].includes(item.kind)){make('p',`${f.price||f.proposed_price||'TBD'} · dostupnosť: ${f.availability||'TBD'}`,card);if(f.summary)make('p',f.summary,card);if(f.added_at||f.updated_at)make('small','Pridané/upravené: '+stamp(f.added_at||f.updated_at),card);}
  else {make('p',f.summary||f.objective||f.open_questions||'Detail v canonical zdroji.',card);if(item.kind==='decision'){make('small','Prečo: '+(f.why_needed||'TBD'),card);make('small','Blokuje: '+(f.what_blocks||'TBD'),card);}}
  make('small',freshness(sourceFor(item)||{}).label+(sourceFor(item)?.status!=='ok'?' · obnova nedostupná':''),card);canonical(item,card);
 }
 function detail(item){
  panel.replaceChildren();action('Zavrieť',()=>panel.close(),panel).className='detail-close';make('p','READ-ONLY / CANONICAL EVIDENCIA',panel,'eyebrow');make('h2',item.title,panel);
  make('p',`ID: ${item.id}`,panel,'detail-id');const dl=make('dl',null,panel,'dash-fields');
  for(const [key,value]of Object.entries(item.fields)){make('dt',labels[key]||key,dl);make('dd',key==='task_status'?taskLabel(value):key==='publication'?publicationLabel(item):(value&&typeof value==='object'?JSON.stringify(value,null,2):String(value??'TBD')),dl);}
  if(item.conflicts.length){make('h3','Konflikty — potrebné rozhodnutie',panel);for(const c of item.conflicts){make('p',labels[c.field]||c.field,panel);for(const v of c.values)make('p',`${v.value} · ${state.data.sources.find(s=>s.id===v.source_id)?.title||v.source_id}`,panel);}}
  make('h3','Pôvod a čerstvosť',panel);const s=sourceFor(item);make('p',`${item.provenance.owner} · ${item.provenance.identity} · ${item.provenance.anchor}`,panel);if(item.provenance.field_sources)for(const [field,id]of Object.entries(item.provenance.field_sources))make('small',`${labels[field]||field}: ${state.data.sources.find(s=>s.id===id)?.title||id}`,panel,'detail-link');make('p',freshness(s||{}).label,panel);make('p','Úprava zdroja: '+stamp(s?.modified_at),panel);canonical(item,panel);
  for(const link of item.links){const url=safeUrl(link.url);if(url){const a=make('a',(link.label||link.role)+' ↗',panel,'detail-link');a.href=url;a.target='_blank';a.rel='noopener noreferrer';}}
  make('h3','Súvisiace položky a zdroje',panel);for(const id of item.related_ids){const related=state.data.items.find(i=>i.id===id);if(related)action(related.title,()=>detail(related),panel);else make('p',id+' · MISSING / nenájdené v načítanom rozsahu',panel);}
  if(!state.demo)action('Zobraziť zdroj v mape',()=>{panel.close();navigate('map');focusMap(item.provenance.file_id,item.source_id,s?.url);},panel);
  panel.showModal();
 }
 function group(title,items,parent,limit=null,note=''){
  const box=make('section',null,parent,'dash-group');box.dataset.title=title;make('h3',title,box);if(note)make('p',note,box,'section-note');
  if(!items.length){make('p',state.data?.sources.some(s=>s.id!=='coverage:campaign-details'&&s.status!=='ok')?'V dostupnej evidencii nič nenájdené; časť zdrojov je nedostupná.':'V načítanom rozsahu nie je evidovaná položka.',box,'empty-row');return;}
  if(limit&&items.length>limit){make('p',`Zobrazených ${limit} z ${items.length} položiek.`,box,'dash-total');if(items[0]?.kind==='task'){const showAll=action('Zobraziť všetky NOW položky',()=>{navigate('now');},box);}else action('Všetky položky →',()=>navigate(items[0]?.kind==='decision'?'decisions':items[0]?.kind==='campaign'||items[0]?.kind==='output'?'campaigns':'sources'),box);}
  const grid=make('div',null,box,'dash-grid');for(const i of(limit?items.slice(0,limit):items))itemCard(i,grid);
 }
 function metricsView(parent){
  const m=metrics(state.data),box=make('section',null,parent,'metric-panel');make('h3','Stav načítanej evidencie',box);
  const tiles=make('div',null,box,'metric-tiles');for(const [label,count,target]of [['Nápady',m.ideas,'direction'],['NOW úlohy',m.tasks,'now'],['Kampane',m.campaigns,'campaigns'],['FB výstupy',m.outputs,'campaigns'],['Aktívne služby',views(state.data).activeServices.length,'offers'],['Návrhy služieb',views(state.data).serviceIdeas.length,'offers']])action(count+' · '+label,()=>navigate(target),tiles);
  make('h4','Nápady podľa stavu evidencie',box);const chart=make('div',null,box,'idea-chart');
  const colors=['#ED0D5B','#0F1D30','#8A0224','#526073','#FDF1F5'];let at=0;const stops=[];for(const [i,[label,count]]of m.stages.entries()){const end=at+count/Math.max(1,m.ideas)*100;stops.push(`${colors[i%colors.length]} ${at}% ${end}%`);at=end;}
  const donut=make('div',null,chart,'idea-donut');donut.style.background=m.ideas?`conic-gradient(${stops.join(',')})`:'#F4F5F9';donut.setAttribute('role','img');donut.setAttribute('aria-label',m.stages.map(([s,n])=>s+': '+n).join(', ')||'Žiadny evidovaný nápad');make('strong',String(m.ideas),donut);
  const legend=make('ul',null,chart,'chart-legend');for(const [i,[label,count]]of m.stages.entries()){const row=make('li',null,legend);make('span',null,row,'chart-key').style.background=colors[i%colors.length];action(label+' · '+count,()=>{navigate('direction');filter=label;render();},row);}
  make('p',m.partial?'Čiastočné pokrytie: niektoré zdroje sú nedostupné.':'Počty položiek v načítanom rozsahu.',box,'section-note');make('p',`Konflikty: ${m.conflicts} · Stavy nápadov neznamenajú approval.`,box,'section-note');make('small','Projekcia: '+stamp(state.data.generated_at),box);
 }
 function statusBadge(value,parent){const badge=make('span',String(value||'TBD'),parent,'dash-badge');badge.dataset.tone=statusTone(value);return badge;}
 function sectionHeading(title,parent,note=''){const box=make('section',null,parent,'dash-group');box.dataset.title=title;make('h3',title,box);if(note)make('p',note,box,'section-note');return box;}
 function tableShell(title,columns,parent,note=''){const box=sectionHeading(title,parent,note),wrap=make('div',null,box,'table-scroll'),table=make('table',null,wrap,'report-table');table.setAttribute('aria-label',title);const row=make('tr',null,make('thead',null,table));for(const col of columns)make('th',col,row).scope='col';return {box,body:make('tbody',null,table)};}
 function servicesTable(title,items,parent){const {box,body}=tableShell(title,['Názov','Popis','Cena','Lifecycle','Aktuálne dostupná'],parent);for(const item of items){const row=make('tr',null,body),name=make('td',null,row);const button=action(itemTitle(item),()=>detail(item),name);button.className='table-title';button.title=item.id;make('small',item.id,name,'table-id');make('td',item.fields.summary||'TBD',row,'description-cell');make('td',item.fields.price||item.fields.proposed_price||'TBD',row,'price-cell');statusBadge(item.fields.lifecycle||item.fields.evidence_status,make('td',null,row));make('td',item.fields.availability||'TBD',row);if(item.conflicts.length)make('small','Konflikt evidencie',name,'conflict-label');}if(!items.length)make('p','Žiadne položky v načítanom rozsahu.',box,'empty-row');}
 function taskRows(title,items,parent,limit=null,showAll=false,{byCategory=false,addedDates=false}={}){
  const box=sectionHeading(title,parent),selected=limit?items.slice(0,limit):items;
  const groups=byCategory?groupTasksByCategory(selected):[{category:null,items:selected}];
  for(const group of groups){const container=group.category?make('div',null,box,'now-category'):box;if(group.category)make('h4',`${group.category} · ${group.items.length}`,container,'now-category-heading');const list=make('div',null,container,'task-list');
   for(const item of group.items){const row=make('article',null,list,'task-row');row.dataset.tone=statusTone(item.fields.priority);const meta=make('div',null,row,'task-meta');statusBadge(item.fields.priority,meta);statusBadge(taskLabel(item.fields.task_status),meta);make('small',item.fields.owner||'Vlastník TBD',meta);if(addedDates)make('small',`Pridané: ${new Intl.DateTimeFormat('sk-SK',{timeZone:'UTC'}).format(nowAddedDate(item))}`,meta);const body=make('div',null,row,'task-body');action(itemTitle(item),()=>detail(item),body).className='card-title';make('p',item.fields.next_step||'Ďalší krok TBD',body);}
  }
  if(!selected.length)make('p',addedDates?'Poradie nie je dostupné: NOW položky nemajú doložený platný dátum pridania.':'Žiadny doložený krok v načítanom rozsahu.',box,'empty-row');
  if(addedDates)make('p','Posledných 5 podľa dátumu pridania do zoznamu úloh. Položky s TBD alebo neplatným dátumom sa do poradia nezaraďujú.',box,'section-note');
  if(showAll)action('Show all NOW →',()=>navigate('now'),box);
 }

 function evidenceLink(link,parent,label='✓ Available'){if(!link){make('span','✕ Missing',parent,'missing-evidence');return;}const url=safeUrl(link.url);if(!url){make('span','✕ Missing',parent,'missing-evidence');return;}const a=make('a',label,parent);a.href=url;a.target='_blank';a.rel='noopener noreferrer';}
 function campaignSections(items,parent){for(const key of ['DRAFT','PREPARING','READY','RUNNING','COMPLETED / EXECUTED','REVIEW']){const selected=items.filter(i=>campaignGroup(i)===key);if(key==='COMPLETED / EXECUTED'&&!selected.length)continue;const {box,body}=tableShell(key,['Campaign / lifecycle','Cieľ','Začiatok','Ďalší krok','Brief','Poster/assets','Publication','Výsledky'],parent,key==='REVIEW'?'Konfliktný alebo nezaradený lifecycle. Canonical status nemeníme.':'');box.dataset.tone=statusTone(key);for(const item of selected){const evidence=evidenceFor(item,state.data),row=make('tr',null,body,'campaign-row');row.dataset.tone=statusTone(key);const name=make('td',null,row);action(itemTitle(item),()=>detail(item),name).className='table-title';const raw=String(item.fields.lifecycle||'TBD');const badge=statusBadge(raw.match(/^[A-Z_]+/)?.[0]||raw,name);badge.title=raw;for(const value of [item.fields.objective,item.fields.start,item.fields.next_step||item.fields.pending]){const cell=make('td',null,row);const text=make('p',value||'TBD',cell,'cell-summary');text.title=value||'TBD';}const briefCell=make('td',null,row);if(evidence.brief&&item.fields.brief_availability!=='UNAVAILABLE')evidenceLink(evidence.brief,briefCell,'YES · Open brief ↗');else make('span',item.fields.brief_availability==='UNAVAILABLE'?'UNAVAILABLE':'NO · CAMPAIGN BRIEF MISSING',briefCell,'missing-evidence');const assets=make('td',null,row);if(evidence.asset)evidenceLink(evidence.asset,assets,'YES · Poster ↗');else if(evidence.folder)evidenceLink(evidence.folder,assets,'YES · Open assets ↗');else make('span','NO',assets,'missing-evidence');make('td',publicationLabel(item),row);const result=make('p',item.fields.results||'TBD',make('td',null,row),'cell-summary');result.title=item.fields.results||'TBD';if(item.conflicts.length)make('small','Konflikt — pozri detail',name,'conflict-label');}if(!selected.length){box.querySelector('.table-scroll').remove();make('p','Žiadne kampane v tomto stave.',box,'empty-row');}}}
 function postsTable(items,parent){const {box,body}=tableShell('FB POSTS',['Cieľ FB postu','MD popis / brief','Plagát / obrázok','Status','Campaign','Publication'],parent,'Odkaz nie je potvrdenie schválenia ani dostupnosti súboru na platforme.');for(const item of items){const post=postDisplay(item,state.data),row=make('tr',null,body),name=make('td',null,row);action(post.title,()=>detail(item),name).className='table-title';make('p',post.objective,name);evidenceLink(post.brief,make('td',null,row));evidenceLink(post.asset,make('td',null,row));statusBadge(post.status,make('td',null,row));make('td',post.campaigns.map(i=>i.title).join(', ')||'TBD',row);make('td',publicationLabel(item),row);}if(!items.length)make('p','Žiadne FB výstupy v načítanom rozsahu.',box,'empty-row');}
 function sourceStatus(){const status=dataStatus(state.data),bar=make('div',null,root,'data-status');make('strong','DATA',bar);action(`${status.available}/${status.total} available`,()=>navigate('sources'),bar);if(status.missing.length){statusBadge(status.missing.length+' missing',bar).dataset.tone='danger';make('span','Missing: '+status.missing.map(s=>s.title).join(', '),bar);}if(status.stale.length){const stale=action(status.stale.length+' stale',()=>navigate('sources'),bar);stale.dataset.tone='warning';stale.title=status.stale.map(s=>s.title).join(', ');}statusBadge(state.demo?'DEMO':'READ ONLY',bar);}
 function sourceView(){
  const box=make('section',null,root,'dash-group');make('h3','Pokrytie a čerstvosť',box);make('p','Čas úspešného čítania, úpravy dokumentu a zostavenia projekcie majú odlišný význam. Chyba zdroja neznamená prázdny zoznam.',box);
  const sourceGrid=make('div',null,box,'source-grid');for(const s of state.data.sources.filter(s=>s.id!=='coverage:campaign-details')){const card=make('article',null,sourceGrid,'source-row');make('h4',s.title,card);make('p',`${s.status.toUpperCase()} · ${freshness(s).label}`,card);make('p','Posledné úspešné čítanie: '+stamp(s.last_success_at)+' · Úprava zdroja: '+stamp(s.modified_at),card);if(s.error)make('p',s.error,card,'conflict-label');if(s.warning)make('p',s.warning,card);const url=safeUrl(s.url);if(url){const a=make('a','Otvoriť zdroj ↗',card);a.href=url;a.target='_blank';a.rel='noopener noreferrer';}}
  group('Dátové medzery',views(state.data).dataGaps,root);metricsView(root);const conflicts=state.data.items.filter(i=>i.conflicts.length);group('Nevyriešené konflikty',conflicts,root);make('p','Projekcia zostavená: '+stamp(state.data.generated_at),root);
 }
 function render(){
  root.hidden=section==='map';map.hidden=section!=='map';for(const b of nav.querySelectorAll('button'))b.setAttribute('aria-current',b.dataset.section===section?'page':'false');if(section==='map'){window.dispatchEvent(new Event('resize'));return;}
  root.replaceChildren();const heading=make('div',null,root,'dash-heading');make('div',null,heading,'dash-heading-copy');make('p','LADY FITNESS / CEO CONTROL CENTER',heading.firstChild,'eyebrow');make('h2',SECTIONS.find(s=>s[0]===section)[1],heading.firstChild);
  const refresh=action('Obnoviť report',async()=>{if(liveConnected){try{await refreshLive();}catch(e){state.fail(e.message);render();}return;}if(state.demo)state.accept(demoProjection());else if(savedSnapshot)state.accept(savedSnapshot);recalculatedAt=new Date().toISOString();render();},heading);refresh.disabled=!state.data&&!liveConnected;refresh.title=liveConnected?'Načíta aktuálny GitHub main. Sheets a Drive sa nemenia.':'Prepočíta načítaný snapshot. Pre živý GitHub pripoj službu.';
  action('Importovať snapshot',()=>document.getElementById('import').click(),heading);
  if(state.data)action('Export pre AI · JSON',()=>{const v=views(state.data);const report={format:'lf-ceo-review',version:2,exported_at:new Date().toISOString(),snapshot_at:state.data.generated_at,import:importRecord,filters:{section,query,filter,fields:fieldFilters},coverage:campaignCoverage(state.data),metrics:metrics(state.data),views:Object.fromEntries(Object.entries(v).map(([key,items])=>[key,items.map(i=>i.id)])),sources:state.data.sources,items:state.data.items};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='LF_CEO_AI_REVIEW.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},heading);
  if(importRecord)action('Vymazať uložený snapshot',()=>document.getElementById('forget').click(),heading);
  action(state.demo?'Zavrieť demo':'Pozrieť syntetické demo',()=>{},heading).onclick=()=>{const wasDemo=state.demo;state.clear();if(!wasDemo){state.demo=true;state.accept(demoProjection());}else if(savedSnapshot)state.accept(savedSnapshot);render();};
  const meta=make('details',null,root,'snapshot-details');make('summary',liveConnected?'Živý GitHub · ručná obnova reportu':'Snapshot režim · pripoj službu pre živý GitHub',meta);make('p',liveConnected?'NOW, strategický kontext a campaign briefy: GitHub main. Načítanie pri pripojení; ďalšie aktualizácie cez Obnoviť report. Sheets / Drive: posledný import.':'Obnovenie reportu prepočíta import; živé Markdown dáta vyžadujú pripojenie služby.',meta);if(state.data?.live_github_at)make('p','GitHub synchronizácia: '+stamp(state.data.live_github_at)+' · main '+state.data.live_github_revision,meta);
  if(importRecord){make('p',`Posledný import: ${stamp(importRecord.importedAt)} · ${importRecord.filename} · ${importRecord.persisted?'uložené v tomto prehliadači':'iba táto relácia'}`,meta);if(importRecord.note)make('p',importRecord.note,meta);}
  if(state.data)make('p',`Zdrojový snapshot: ${stamp(state.data.generated_at)} · vek: ${snapshotAge(state.data.generated_at)}${recalculatedAt?' · Report prepočítaný: '+stamp(recalculatedAt):''}`,meta);
  if(state.demo)make('p','DEMO · Všetky položky sú syntetické. Nejde o aktuálny stav Lady Fitness.',root,'dash-alert demo-alert');
  if(state.error)make('p',state.error+(state.data?' Posledný úspešný snapshot zostáva označený svojím vekom.':''),root,'dash-alert');
  if(!state.data){make('h3',importRecord?.graphOnly?'Graf je načítaný; business údaje v ňom nie sú.':'Importuj dashboard snapshot.',root);make('p',importRecord?.graphOnly?'Inventár súborov neobsahuje potvrdené ceny, priority ani stavy kampaní. Pre tieto údaje importuj dashboard projekciu alebo spoločný snapshot. Pôvodná mapa zostáva dostupná.':'Importuj JSON dashboard projekcie alebo spoločný snapshot s grafom. Dáta sa vedomým importom uložia iba v tomto prehliadači, nikam sa neodosielajú. Zabezpečená služba zostáva voliteľná pre mapu a históriu operácií.',root);if(importRecord?.graphOnly)action('Otvoriť mapu',()=>navigate('map'),root);return;}
  sourceStatus();
  if(section==='sources'){sourceView();return;}
  let v=views(state.data);
  if(section!=='overview'){
   const controls=make('div',null,root,'dash-filters'),input=make('input',null,controls);input.type='search';input.placeholder='Hľadať v tomto pohľade…';input.setAttribute('aria-label','Hľadať položky dashboardu');input.value=query;input.oninput=()=>{query=input.value;const pos=input.selectionStart;render();const next=root.querySelector('.dash-filters input');next.focus();next.setSelectionRange(pos,pos);};
   const sel=make('select',null,controls);sel.setAttribute('aria-label','Filter stavu');const statuses=[...new Set(state.data.items.flatMap(i=>[i.fields.lifecycle,i.fields.evidence_status,i.fields.creative,i.fields.approval]).filter(Boolean))].sort();sel.append(new Option('Všetky stavy',''));for(const x of statuses)sel.append(new Option(x,x));sel.value=filter;sel.onchange=()=>{filter=sel.value;render();};
   const keys=section==='now'?['priority','task_status','category','owner']:section==='offers'?['availability','audience','type']:[];for(const key of keys){const select=make('select',null,controls);select.setAttribute('aria-label',labels[key]||key);select.append(new Option(labels[key]||key,''));for(const value of [...new Set(state.data.items.filter(i=>section==='now'?i.kind==='task':i.kind==='service').map(i=>key==='category'?taskCategory(i):i.fields[key]).filter(Boolean))].sort())select.append(new Option(value,value));select.value=fieldFilters[key]||'';select.onchange=()=>{fieldFilters[key]=select.value;render();};}
   const match=i=>Object.entries(fieldFilters).every(([key,value])=>!value||(key==='category'?taskCategory(i):i.fields[key])===value)&&searchText(i.title+' '+i.id).includes(searchText(query))&&(!filter||Object.values(i.fields).includes(filter));v=Object.fromEntries(Object.entries(v).map(([k,a])=>[k,a.filter(match)]));
  }
  if(section==='overview'){
   const layout=make('div',null,root,'overview-stack');const summary=sectionHeading('Executive Summary',layout);make('p',`Načítaný register obsahuje ${v.now.length} operatívnych úloh; NEXT vyberá ${v.next.length} konkrétnych krokov s prioritou P0/P1. Aktívnych služieb je ${v.activeServices.length}; dostupnosť zostáva samostatným údajom. ${v.decisions.length} položiek má explicitnú evidenciu business rozhodnutia. Konfliktné kampane sa nezobrazujú ako jednoznačne bežiace.`,summary);summary.classList.add('executive-summary');
   group('Aktuálny smer',v.direction,layout,2);taskRows('Dôležité teraz',v.now,layout,5,true,{byCategory:true});taskRows('NEXT STEPS',v.next,layout,5,false,{byCategory:true});
   const recent=v.changes.filter(i=>i.fields.business_verified===true&&dateValue(i.fields.date)!==null&&Date.now()-dateValue(i.fields.date)>=0&&Date.now()-dateValue(i.fields.date)<=7*86400000);const changes=sectionHeading('LAST BUSINESS DIRECTION CHANGES',layout);if(recent.length){const grid=make('div',null,changes,'dash-grid');for(const i of recent.slice(0,5))itemCard(i,grid);}else make('p','No verified business direction changes available.',changes,'empty-row');
   taskRows('NEW NOW items ADDED',latestNowItems(state.data),layout,null,false,{addedDates:true});
  }else if(section==='now'){taskRows('Úplný register NOW',v.now,root);}
  else if(section==='decisions'){group('Business rozhodnutia vlastníka',v.decisions,root,null,'Iba explicitne klasifikované business rozhodnutia. Chýbajúce polia patria do Kvality dát.');action('Dátové medzery →',()=>navigate('sources'),root);}
  else if(section==='campaigns'){campaignSections(v.campaigns,root);postsTable(v.outputs,root);}
  else if(section==='offers'){servicesTable('Aktívne služby',v.activeServices,root);servicesTable('Služby v príprave a pilote',v.preparingServices,root);servicesTable('Nápady a návrhy služieb',v.serviceIdeas,root);if(v.otherServices.length){const collapsed=make('details',null,root,'secondary-section');make('summary',`Ostatné / PAUSED / RETIRED (${v.otherServices.length})`,collapsed);servicesTable('Ostatné služby',v.otherServices,collapsed);}servicesTable('Nové retailové návrhy',v.ideas.filter(i=>i.id.startsWith('LF-PROP-')),root);}
  else{group('Zaznamenaný smer a ciele',v.direction,root);for(const bucket of ['FOCUS NOW','LATER','PARKED','UNCLASSIFIED'])group(bucket,v.ideas.filter(i=>ideaBucket(i)===bucket),root,null,'Zaradenie vyžaduje explicitnú evidenciu; NOW úlohy sú samostatný register.');metricsView(root);}
 }
 render();return {navigate,setLiveConnected(value){liveConnected=value;render();},acceptLive(raw){state.accept(mergeLiveReport(state.data,raw));state.error='';render();},liveError(message){state.fail(message);render();},importError(message){state.fail(message);render();},clear(){liveConnected=false;importRecord=null;savedSnapshot=null;recalculatedAt=null;state.clear();panel.close();panel.replaceChildren();render();},importSnapshot(projection,record){const checked=projection?new DashboardState():null;if(checked)checked.accept(projection);state.clear();savedSnapshot=checked?.data||null;importRecord={...record};recalculatedAt=null;if(savedSnapshot)state.accept(savedSnapshot);panel.close();render();},diagnostics:()=>({items:state.data?.items.length||0,demo:state.demo,error:state.error,section,mode:liveConnected?'github-live':'snapshot',importedAt:importRecord?.importedAt||null})};
}
