import {validateProjection} from './dashboard-model.mjs?v=20261008-live-v6';
// GitHub owns Markdown fields; register conflicts remain explicit, never owner-approved here.
export function mergeLiveReport(previous,raw){const live=validateProjection(raw);if(!previous)return live;const base=validateProjection(previous),replaced=new Set(base.sources.filter(s=>['now','direction'].includes(s.role)||s.provider==='github'&&['brief','coverage'].includes(s.role)).map(s=>s.id));
 const items=base.items.flatMap(i=>{if(!replaced.has(i.source_id))return [i];const register=i.provenance.field_sources?.registry_lifecycle;if(i.kind==='campaign'&&register&&i.fields.registry_fields)return [{...i,source_id:register,fields:{...i.fields.registry_fields,storage_slug:i.fields.storage_slug},links:i.links.filter(l=>l.role!=='brief'),conflicts:i.conflicts.filter(c=>!c.values?.some(v=>replaced.has(v.source_id)))}];return [];}),campaigns=items.filter(i=>i.kind==='campaign');
 for(const item of live.items){if(item.kind!=='campaign'){items.push(item);continue;}const old=campaigns.find(i=>i.id===item.id||i.fields.storage_slug&&i.fields.storage_slug===item.fields.storage_slug);if(!old){items.push(item);continue;}
  const priorSource=old.source_id;for(const key of ['lifecycle','approval','publication']){const registered=old.fields['registry_'+key]??old.fields[key],value=item.fields[key];old.fields['registry_'+key]=registered;if(registered&&value&&registered!==value&&!/^(TBD|MISSING)/.test(value))old.conflicts.push({field:key,values:[{value:registered,source_id:priorSource},{value,source_id:item.source_id}]});}
  old.conflicts=[...new Map(old.conflicts.map(c=>[JSON.stringify(c),c])).values()];old.fields={...old.fields,...item.fields,registry_fields:old.fields.registry_fields||{...old.fields}};old.links=[...old.links.filter(l=>l.role!=='brief'),...item.links];old.related_ids=[...new Set([...old.related_ids,...item.related_ids])];old.provenance={...old.provenance,field_sources:{...old.provenance.field_sources,registry_lifecycle:priorSource,lifecycle:item.source_id},additional_sources:[...new Set([...(old.provenance.additional_sources||[]),item.source_id])]};
 }
 const referenced=new Set(items.map(i=>i.source_id));const sources=[...base.sources.filter(s=>!live.sources.some(l=>l.id===s.id)&&(!replaced.has(s.id)||referenced.has(s.id))),...live.sources];
 return validateProjection({...base,sources,items,live_github_at:live.generated_at,live_github_revision:live.sources.find(s=>s.role==='now')?.revision});}
