import {statusTerminal,statusLabel,statusOptions,statusDomain,configureStatusCatalog} from './status-model.mjs?v=20261009-status-registry';
import {statusRank} from './reporting.mjs?v=20261009-supabase-v2';
export const WORK=Object.freeze({NOT_STARTED:'Nezačaté',PREPARING:'V príprave',IN_PROGRESS:'Prebieha',BLOCKED:'Blokované',COMPLETED:'Dokončené',CANCELLED:'Zrušené'});
export const day=value=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return null;const d=new Date(value+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===value?value:null;};
export const displayDate=value=>{if(!value)return 'TBD';const d=day(String(value).slice(0,10));return d?d.split('-').reverse().join('-'):'TBD';};
export const displayQuarter=value=>/^(Q[1-4])-?\d{4}$/.test(value||'')?value.replace(/^(Q[1-4])-?(\d{4})$/,'$1-$2'):'TBD';
export const planning=(f,prefix)=>f[prefix+'_date']?displayDate(f[prefix+'_date']):displayQuarter(f[prefix+'_quarter']);
const active=i=>!statusTerminal(i.fields.task_status||i.fields.work_status||i.fields.status||i.fields.lifecycle,i.kind==='campaign'?'campaign':i.fields.task_status||i.fields.work_status?'work':'lifecycle');
const concrete=v=>typeof v==='string'&&v.trim()&&!/^(TBD|MISSING|NULL)$/i.test(v.trim());
export function filterTaskTable(items,columns,state){
 const normalize=v=>String(v||'TBD').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('sk');
 const selected=items.filter(i=>columns.every(([label,value])=>!state.filters[label]||normalize(value(i)).includes(normalize(state.filters[label]))));
 const column=columns.find(c=>c[0]===state.sort);if(column)selected.sort((a,b)=>{const value=column[2]||column[1],av=value(a)||'TBD',bv=value(b)||'TBD';if(av==='TBD'||av==='9999')return bv==='TBD'||bv==='9999'?a.id.localeCompare(b.id):1;if(bv==='TBD'||bv==='9999')return -1;if(/stav|status/i.test(column[0])&&statusRank(av)!==statusRank(bv))return (statusRank(av)-statusRank(bv))*state.direction;return String(av).localeCompare(String(bv),'sk',{numeric:true})*state.direction||a.id.localeCompare(b.id);});return selected;
}
export function operationalViews(data,today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())){
 configureStatusCatalog(data);
 const items=data?.items||[],tasks=items.filter(i=>i.kind==='task'),entities=items.filter(i=>['service','product','campaign'].includes(i.kind));
 const covered=new Set(tasks.filter(active).flatMap(i=>i.related_ids));
 const derived=entities.filter(i=>!covered.has(i.id)&&active(i)&&((i.kind==='campaign'&&['IDEA','DRAFT','PREPARING','IN_REVIEW','PUBLISHED'].includes(i.fields.status))||['NOT_STARTED','PREPARING','IN_PROGRESS','BLOCKED'].includes(i.fields.work_status))).map(i=>({...i,kind:'task',fields:{...i.fields,task_status:i.fields.work_status||(['IDEA','DRAFT'].includes(i.fields.status)?'NOT_STARTED':i.fields.status==='PUBLISHED'?'IN_PROGRESS':'PREPARING'),category:i.fields.category||'Kampane',derived_from:i.id}}));
 const now=[...tasks,...derived].sort((a,b)=>({P0:0,P1:1,P2:2}[a.fields.priority]??9)-({P0:0,P1:1,P2:2}[b.fields.priority]??9)||(a.fields.due_date||'9999').localeCompare(b.fields.due_date||'9999')||a.id.localeCompare(b.id));
 const actionable=now.filter(i=>active(i)&&i.fields.task_status!=='BLOCKED');const end=new Date(today+'T00:00:00Z');end.setUTCDate(end.getUTCDate()+5);const until=end.toISOString().slice(0,10),currentQuarter=today.slice(0,4)+'-'+(Math.floor((Number(today.slice(5,7))-1)/3)+1);const futureQuarter=q=>/^Q[1-4]-?\d{4}$/.test(q||'')&&(q.slice(-4)+'-'+q[1])>=currentQuarter;
 const schedule=items.filter(i=>['task','service','product','campaign'].includes(i.kind));const overdue=now.filter(i=>active(i)&&day(i.fields.due_date)&&i.fields.due_date<today),dueSoon=now.filter(i=>active(i)&&day(i.fields.due_date)&&i.fields.due_date>=today&&i.fields.due_date<=until);
 const calendar=[],quarters=[];for(const i of schedule)for(const prefix of ['due','planned_completion','launch']){const exact=day(i.fields[prefix+'_date']);if(exact)calendar.push({item:i,type:prefix,date:exact});else if(i.fields[prefix+'_quarter'])quarters.push({item:i,type:prefix,quarter:displayQuarter(i.fields[prefix+'_quarter'])});}
 calendar.sort((a,b)=>a.date.localeCompare(b.date)||a.item.id.localeCompare(b.item.id));
 return {tasks:[...tasks].sort((a,b)=>({P0:0,P1:1,P2:2}[a.fields.priority]??9)-({P0:0,P1:1,P2:2}[b.fields.priority]??9)||a.id.localeCompare(b.id)),now,important:actionable.filter(i=>['P0','P1'].includes(i.fields.priority)).slice(0,5),next:actionable.filter(i=>concrete(i.fields.next_step)).slice(0,5),dueSoon,overdue,launches:entities.filter(i=>active(i)&&((day(i.fields.launch_date)&&i.fields.launch_date>=today)||futureQuarter(i.fields.launch_quarter))),calendar,quarters,services:items.filter(i=>i.kind==='service'),products:items.filter(i=>i.kind==='product'),campaigns:items.filter(i=>i.kind==='campaign'),outputs:items.filter(i=>i.kind==='output'),assets:items.filter(i=>i.kind==='asset'),performance:items.filter(i=>i.kind==='performance')};
}
export function renderOperational({data,section,parent,make,action,detail,statusBadge,taskRows,tableShell,evidenceLink,query='',filter='',taskTableState={filters:{},sort:'Priorita',direction:1},onTaskTableChange=()=>{}}){
 const v=operationalViews(data),matches=i=>(i.title+' '+i.id+' '+(i.fields.category||'')).toLocaleLowerCase('sk').includes(query.toLocaleLowerCase('sk'))&&(!filter||Object.values(i.fields).includes(filter));
 const table=(title,items,columns)=>{const {box,body}=tableShell(title,columns.map(c=>c[0]),parent);for(const i of items.filter(matches)){const row=make('tr',null,body);for(const [label,value]of columns){const cell=make('td',null,row);if(label==='Názov'){action(i.title,()=>detail(i),cell).className='table-title';make('small',i.id,cell);}else if(['Stav','Práca','Priorita','Dostupnosť','Schválenie','Publikovanie'].includes(label)){const field=label==='Stav'?(i.kind==='task'?'status':i.kind==='campaign'?'status':'lifecycle'):label==='Práca'?'work_status':label==='Priorita'?'priority':label==='Dostupnosť'?(i.kind==='service'?'availability_status':'stock_status'):label==='Schválenie'?'approval':'publication';statusBadge(value(i),cell,statusDomain(i,field)||(field==='approval'?'output_approval':field==='publication'?'output_publication':undefined));}else make('span',value(i)??'TBD',cell);}}if(!items.length)make('p','Žiadne položky v načítanom rozsahu.',box,'empty-row');return box;};
 const euro=n=>n==null?'TBD':new Intl.NumberFormat('sk-SK',{style:'currency',currency:'EUR'}).format(n);
 const entityColumns=[['Názov',i=>i.title],['Kategória',i=>i.fields.category],['Publikum',i=>i.fields.audience],['Stav',i=>i.fields.lifecycle],['Dostupnosť',i=>i.fields.availability_status||i.fields.stock_status],['Priorita',i=>i.fields.priority],['Práca',i=>data.origin==='supabase'?i.fields.work_status:(WORK[i.fields.work_status]||i.fields.work_status||'TBD')],['Aktuálna cena',i=>euro(i.fields.current_price_eur)],['Navrhovaná cena',i=>euro(i.fields.proposed_price_eur)],['Plán dokončenia',i=>planning(i.fields,'planned_completion')],['Spustenie',i=>planning(i.fields,'launch')],['Termín',i=>displayDate(i.fields.due_date)],['Ďalší krok',i=>i.fields.next_step]];
 const campaignTable=(title,items)=>table(title,items,[['Názov',i=>i.title],['Stav',i=>i.fields.status],['Progres',i=>i.fields.progress_pct==null?'TBD':i.fields.progress_pct+'%'],['Priorita',i=>i.fields.priority],['Cieľ',i=>i.fields.objective],['Publikum',i=>i.fields.audience],['Spustenie',i=>planning(i.fields,'launch')],['Dokončenie',i=>planning(i.fields,'planned_completion')],['Termín',i=>displayDate(i.fields.due_date)],['Ďalší krok',i=>i.fields.next_step],['Súvisiace IDs',i=>i.related_ids.join(', ')],['Výsledky',i=>i.fields.results_summary],['Poučenie',i=>i.fields.campaign_learning]]);
 const counts=()=>{const box=make('section',null,parent,'metric-panel');make('h3','Register Supabase',box);const tiles=make('div',null,box,'metric-tiles');for(const [label,items]of [['Služby',v.services],['Produkty',v.products],['Kampane',v.campaigns],['NOW',v.now],['Schválené výstupy',v.outputs]])make('strong',items.length+' · '+label,tiles);};
 const quality=()=>{const box=make('section',null,parent,'dash-group');make('h3','Kvalita dát',box);const summary=data.validation?.summary||[];make('p',`ERROR: ${summary.find(r=>r.severity==='ERROR')?.issue_count??0} · WARN: ${summary.find(r=>r.severity==='WARN')?.issue_count??0}`,box);if(section==='sources'){const {body:t}=tableShell('Pravidlá kvality dát',['severity','rule_code','business_id','table_name'],box);for(const issue of data.validation?.issues||[]){const row=make('tr',null,t);for(const key of ['severity','rule_code','business_id','table_name']){const cell=make('td',null,row);if(key==='severity')statusBadge(issue[key],cell,'severity');else make('span',issue[key]||'TBD',cell);};}make('p','Pravidlá označujú chýbajúce alebo legacy fakty. Hodnoty sa nedopĺňajú odhadom.',box);}};
 if(section==='overview'){counts();const summary=make('section',null,parent,'dash-group');make('h3','Executive Summary',summary);make('p',`${v.services.length} služieb · ${v.products.length} produktov · ${v.campaigns.length} kampaní. NOW odvodzuje úlohy a súvisiacu prácu bez duplicitného zaradenia entity.`,summary);for(const [title,items]of [['Dôležité teraz',v.important],['NEXT STEPS',v.next],['Due Soon · do 5 dní',v.dueSoon],['Overdue',v.overdue]])taskRows(title,items,parent,null,false,{byCategory:true});table('Upcoming Launches',v.launches,[['Názov',i=>i.title],['Spustenie',i=>planning(i.fields,'launch')]]);campaignTable('Campaign snapshot',v.campaigns);quality();return;}
 if(section==='tasks'){
  const columns=[['ID',i=>i.id],['Názov',i=>i.title],['Kategória',i=>i.fields.category],['Priorita',i=>i.fields.priority],['Stav',i=>data.origin==='supabase'?(i.fields.task_status||i.fields.status):(WORK[i.fields.task_status||i.fields.status]||i.fields.task_status||i.fields.status||'TBD')],['Zodpovednosť',i=>i.fields.owner],['Termín',i=>displayDate(i.fields.due_date),i=>i.fields.due_date||'9999'],['Plán dokončenia',i=>planning(i.fields,'planned_completion'),i=>i.fields.planned_completion_date||(i.fields.planned_completion_quarter?i.fields.planned_completion_quarter.slice(-4)+'-'+(Number(i.fields.planned_completion_quarter[1])*3-2).toString().padStart(2,'0')+'-01':'9999')],['Ďalší krok',i=>i.fields.next_step]];
  table('Všetky úlohy',v.tasks,columns);return;
 }
 if(section==='now'){taskRows('Management / odvodený NOW',v.now.filter(matches),parent,null,false,{byCategory:true});return;}
 if(section==='offers'){table('Aktívne služby',v.services.filter(i=>i.fields.lifecycle==='ACTIVE'),entityColumns);table('Služby · nápady, príprava a ostatné',v.services.filter(i=>i.fields.lifecycle!=='ACTIVE'),entityColumns);return;}
 if(section==='products'){for(const lifecycle of ['ACTIVE','IDEA'])table(statusLabel(lifecycle,'lifecycle')+' produkty',v.products.filter(i=>i.fields.lifecycle===lifecycle),entityColumns);table('Ostatné produkty',v.products.filter(i=>!['ACTIVE','IDEA'].includes(i.fields.lifecycle)),entityColumns);return;}
 if(section==='calendar'){for(const [title,entries,key]of [['Presné dátumy',v.calendar,'date'],['Plánovanie iba po štvrťrokoch',v.quarters,'quarter']]){const box=make('section',null,parent,'dash-group');make('h3',title,box);for(const entry of entries)if(matches(entry.item)){const row=make('div',null,box,'task-row');make('span',key==='date'?displayDate(entry.date):entry.quarter,row);action(entry.item.title,()=>detail(entry.item),row);make('small',entry.type,row);}if(!entries.length)make('p','Žiadne potvrdené termíny.',box);}return;}
 if(section==='sources'){quality();for(const s of data.sources){make('p',s.title+' · posledné čítanie '+displayDate(s.last_success_at),parent);}return;}
 if(section==='campaigns'){for(const status of (data.origin==='supabase'?statusOptions('campaign').map(s=>s.code):['DRAFT','PREPARING','PUBLISHED','COMPLETED']))campaignTable(statusLabel(status,'campaign'),v.campaigns.filter(i=>i.fields.status===status));
  table('Canonical final approved outputs',v.outputs,[['Názov',i=>i.title],['Campaign',i=>i.fields.campaign_id],['Schválenie',i=>i.fields.approval],['Publikovanie',i=>i.fields.publication],['Platformy',i=>(i.fields.platforms||[]).join(', ')],['Formát',i=>i.fields.format],['Caption',i=>i.fields.caption],['Graphic text',i=>i.fields.graphic_text],['CTA',i=>i.fields.cta],['Schválené',i=>displayDate(i.fields.approved_at)],['Publikované',i=>displayDate(i.fields.published_at)],['References',i=>(i.fields.reference_tags||[]).join(', ')],['Owner feedback',i=>i.fields.owner_feedback]]);
  const box=make('section',null,parent,'dash-group');make('h3','Drive assets · presné odkazy',box);make('p','Odkaz ani is_final nepotvrdzujú dostupnosť, schválenie či publikovanie. Preview nie je načítané; použi odkaz s aktuálnymi Drive oprávneniami.',box);for(const asset of v.assets.filter(a=>a.related_ids.some(id=>v.campaigns.concat(v.outputs).some(i=>i.id===id)))){make('p',asset.title+' · '+asset.fields.drive_file_id+' · '+asset.related_ids.join(', '),box);evidenceLink(asset.links[0],box,'Otvoriť asset ↗');}for(const c of v.campaigns)for(const link of c.links.filter(l=>l.role==='folder'))evidenceLink(link,box,c.title+' · Drive folder ↗');
  if(!v.performance.length)make('p','No performance data yet',parent,'empty-row');else table('Timestamped social performance',v.performance,[['Názov',i=>i.title],...['output_id','platform','measurement_at','reach','views_impressions','reactions_likes','comments','shares','saves','clicks','profile_actions','new_followers','leads_bookings','sales_conversions','revenue_eur','engagement_rate_pct','performance_learning','creative_learning','content_learning'].map(k=>[k,i=>i.fields[k]])]);
 }
}
