import {dateValue,freshness,publicationLabel} from './dashboard-model.mjs?v=20261008-live-v6';
export const LEGACY_COVERAGE_ID='coverage:campaign-details';
export function statusTone(value){const s=String(value||'').trim().toUpperCase();if(['P0','DRAFT','BLOCKED','ERROR','NEZAČATÉ'].includes(s))return 'danger';if(['P1','PREPARING','PLANNED','V PRÍPRAVE'].includes(s))return 'warning';if(['ACTIVE','RUNNING','PREBIEHA','CONFIRMED'].includes(s))return 'success';if(['READY','PILOT','APPROVED'].includes(s))return 'info';return 'neutral';}
// A display grouping, not a write or normalization of canonical lifecycle.
export function campaignGroup(item){if(item.conflicts?.some(c=>['lifecycle','identity'].includes(c.field)))return 'REVIEW';const raw=String(item.fields.lifecycle||'').trim().toUpperCase(),s=raw.match(/^([A-Z_]+)(?=[. /;—]|$)/)?.[1]||raw;return ({DRAFT:'DRAFT',IDEA:'DRAFT',PROPOSED:'DRAFT',PREPARING:'PREPARING',PLANNED:'PREPARING',READY:'READY',RUNNING:'RUNNING',ACTIVE:'RUNNING',COMPLETED:'COMPLETED / EXECUTED',EXECUTED:'COMPLETED / EXECUTED'})[s]||'REVIEW';}
export function dataStatus(data,now=Date.now()){const sources=(data?.sources||[]).filter(s=>s.id!==LEGACY_COVERAGE_ID),missing=sources.filter(s=>s.status!=='ok'),stale=sources.filter(s=>s.status==='ok'&&freshness(s,now).stale);return {total:sources.length,available:sources.length-missing.length,missing,stale,legacyCoverage:(data?.sources||[]).some(s=>s.id===LEGACY_COVERAGE_ID)};}
export function canonicalBrief(item,data){return item.links?.find(l=>l.role==='brief'&&/^https:\/\/github\.com\/wwwsusi\/lady-fitness-core\/blob\//.test(l.url))||null;}
export function evidenceFor(item,data){const related=(data?.items||[]).filter(i=>item.related_ids?.includes(i.id));const campaigns=related.filter(i=>i.kind==='campaign');const brief=canonicalBrief(item,data)||campaigns.map(i=>canonicalBrief(i,data)).find(Boolean)||null;const assetItems=[...related.filter(i=>i.kind==='asset'),...campaigns.flatMap(c=>(data?.items||[]).filter(i=>i.kind==='asset'&&c.related_ids.includes(i.id)))];const links=[...(item.links||[]),...assetItems.flatMap(i=>i.links||[])];const asset=links.find(l=>['asset','poster','image'].includes(l.role)&&/^https:\/\/(drive\.google\.com|docs\.google\.com)\//.test(l.url)&&!l.url.includes('/folders/'))||null;const folder=[...(item.links||[]),...campaigns.flatMap(c=>c.links||[])].find(l=>/^https:\/\/drive\.google\.com\/drive\/folders\//.test(l.url))||null;return {brief,asset,folder,campaigns,assets:assetItems};}
export function postDisplay(item,data){const evidence=evidenceFor(item,data);return {objective:item.fields.objective||'TBD — cieľ konkrétneho postu',title:item.title.replace(/(?:\s*\/\s*)?LF-(?:OUT|ASSET)-[A-Z0-9-]+/g,'').trim()||'Facebook výstup',status:publicationLabel(item).startsWith('Publikov')?'PUBLISHED_REPORTED':item.fields.approval==='APPROVED'&&item.fields.creative==='READY'?'READY':'DRAFT',...evidence};}
export function recentAdditions(data){return (data?.items||[]).filter(i=>(i.kind==='service'&&['IDEA','PROPOSED','PREPARING','PILOT'].includes(i.fields.lifecycle))||(i.kind==='idea'&&i.id.startsWith('LF-PROP-'))).sort((a,b)=>(dateValue(b.fields.added_at||b.fields.updated_at)||0)-(dateValue(a.fields.added_at||a.fields.updated_at)||0)).slice(0,5);}

export const itemTitle=item=>String(item.title).replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/[`*]/g,'');

export function taskCategory(item){return String(item.fields.category||'').trim()||'Kategória TBD';}
export function groupTasksByCategory(items){const groups=new Map();for(const item of items){const raw=taskCategory(item),category=raw&&!/^(TBD|MISSING|UNKNOWN)$/i.test(raw)?raw:'Kategória TBD';if(!groups.has(category))groups.set(category,[]);groups.get(category).push(item);}return [...groups].map(([category,items])=>({category,items}));}
export function nowAddedDate(item){const raw=String(item.fields.added_at||'').trim();const iso=raw.match(/^(\d{4})-(\d{2})-(\d{2})$/),sk=raw.match(/^(\d{1,2})\.\s*(\d{1,2})\.\s*(\d{4})$/);if(!iso&&!sk)return null;const [y,m,d]=iso?iso.slice(1).map(Number):[Number(sk[3]),Number(sk[2]),Number(sk[1])];const date=new Date(Date.UTC(y,m-1,d));return date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d?date.getTime():null;}
export function latestNowItems(data){return (data?.items||[]).filter(i=>i.kind==='task'&&nowAddedDate(i)!==null).sort((a,b)=>nowAddedDate(b)-nowAddedDate(a)).slice(0,5);}
