import {registryStatus,liveStatusCatalog} from './status-model.mjs?v=20261009-status-registry';
import {dateValue,freshness,publicationLabel} from './dashboard-model.mjs?v=20261008-live-v6';
export const LEGACY_COVERAGE_ID='coverage:campaign-details';
export function statusTone(value,domain){const registered=registryStatus(value,domain);if(registered)return registered.color_key;if(liveStatusCatalog())return 'neutral';const s=String(value||'').trim().toUpperCase();if(['P0','BLOCKED','BLOKOVANÉ','ERROR','UNAVAILABLE'].includes(s))return 'danger';if(['P1','PREPARING','PLANNED','READY','V PRÍPRAVE','REVIEW'].includes(s))return 'warning';if(['COMPLETED','EXECUTED','COMPLETED / EXECUTED','DOKONČENÉ','APPROVED','CONFIRMED'].includes(s))return 'success';if(['ACTIVE','RUNNING','IN_PROGRESS','PREBIEHA','PILOT','PUBLISHED','PUBLISHED_REPORTED'].includes(s))return 'info';return 'neutral';}
export const TASK_STATUS_FLOW=Object.freeze(['NOT_STARTED','PREPARING','IN_PROGRESS','BLOCKED','COMPLETED','CANCELLED']);
export function statusRank(value,domain){const registered=registryStatus(value,domain);if(registered)return registered.sort_order;if(liveStatusCatalog())return 999999;const s=String(value||'').trim().toUpperCase();return ({NOT_STARTED:0,'NEZAČATÉ':0,'TO-DO':0,DRAFT:0,IDEA:0,PROPOSED:0,PREPARING:1,'V PRÍPRAVE':1,PLANNED:1,READY:2,PILOT:3,IN_PROGRESS:3,'PREBIEHA':3,ACTIVE:3,RUNNING:3,PUBLISHED:3,PUBLISHED_REPORTED:3,BLOCKED:4,'BLOKOVANÉ':4,PAUSED:4,COMPLETED:5,'DOKONČENÉ':5,EXECUTED:5,'COMPLETED / EXECUTED':5,CANCELLED:6,'ZRUŠENÉ':6,RETIRED:6})[s]??99;}
export const normalizeCell=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('sk').trim();
export function compareCells(a,b,label,direction=1){
 const missing=v=>!v||/^(TBD|NULL|MISSING|—)$/i.test(v);if(missing(a)||missing(b))return missing(a)?(missing(b)?0:1):-1;
 if(/stav|status|lifecycle|práca/i.test(label)){const diff=statusRank(a)-statusRank(b);if(diff)return diff*direction;}
 const date=v=>{const m=String(v).match(/^(\d{2})-(\d{2})-(\d{4})$/);if(m)return m[3]+'-'+m[2]+'-'+m[1];const q=String(v).match(/^Q([1-4])-?(\d{4})$/);return q?q[2]+'-'+String(Number(q[1])*3-2).padStart(2,'0')+'-01':v;};
 return String(date(a)).localeCompare(String(date(b)),'sk',{numeric:true})*direction;
}
export function enhanceTable({table,head,body,columns,box,make,action}){
 const headers=make('tr',null,head),filters=make('tr',null,head),inputs=[],buttons=[],cells=[];let order=-1,direction=1;
 const count=make('p',null,box,'section-note');count.setAttribute('aria-live','polite');
 const update=()=>{let visible=0;for(const row of body.children){row.hidden=!inputs.every((input,index)=>normalizeCell(row.children[index]?.textContent).includes(normalizeCell(input.value)));if(!row.hidden)visible++;}count.textContent=`Zobrazených ${visible} z ${body.children.length} položiek`;if(order>=0){const rows=[...body.children];rows.sort((a,b)=>{const ac=a.children[order],bc=b.children[order],ar=ac?.dataset?.statusRank,br=bc?.dataset?.statusRank;if(ar!==undefined&&br!==undefined)return (Number(ar)-Number(br))*direction;return compareCells(ac?.textContent.trim(),bc?.textContent.trim(),columns[order],direction);});for(const row of rows)body.append(row);}for(let i=0;i<columns.length;i++){cells[i].setAttribute('aria-sort',i===order?(direction===1?'ascending':'descending'):'none');buttons[i].textContent=columns[i]+(i===order?(direction===1?' ↑':' ↓'):'');}};
 for(const [index,label]of columns.entries()){const th=make('th',null,headers);th.scope='col';cells.push(th);buttons.push(action(label,()=>{direction=order===index?-direction:1;order=index;update();},th));const input=make('input',null,make('td',null,filters));input.type='search';input.placeholder='Filtrovať…';input.setAttribute('aria-label',`Filtrovať ${table.getAttribute('aria-label')} · ${label}`);input.style.width='100%';input.oninput=update;inputs.push(input);}
 const reset=action('Zrušiť filtre a zoradenie',()=>{for(const input of inputs)input.value='';order=-1;for(const row of originalRows)body.append(row);update();},box);let originalRows=[];queueMicrotask(()=>{originalRows=[...body.children];update();});return reset;
}
// A display grouping, not a write or normalization of canonical lifecycle.
export function campaignGroup(item){if(item.conflicts?.some(c=>['lifecycle','identity'].includes(c.field)))return 'REVIEW';const raw=String(item.fields.lifecycle||'').trim().toUpperCase(),s=raw.match(/^([A-Z_]+)(?=[. /;—]|$)/)?.[1]||raw;return ({DRAFT:'DRAFT',IDEA:'DRAFT',PROPOSED:'DRAFT',PREPARING:'PREPARING',PLANNED:'PREPARING',READY:'READY',RUNNING:'RUNNING',ACTIVE:'RUNNING',COMPLETED:'COMPLETED / EXECUTED',EXECUTED:'COMPLETED / EXECUTED'})[s]||'REVIEW';}
export function dataStatus(data,now=Date.now()){const sources=(data?.sources||[]).filter(s=>s.id!==LEGACY_COVERAGE_ID),missing=sources.filter(s=>s.status!=='ok'),stale=sources.filter(s=>s.status==='ok'&&freshness(s,now).stale);return {total:sources.length,available:sources.length-missing.length,missing,stale,legacyCoverage:(data?.sources||[]).some(s=>s.id===LEGACY_COVERAGE_ID)};}
export function canonicalBrief(item,data){return item.links?.find(l=>l.role==='brief'&&/^https:\/\/github\.com\/wwwsusi\/lady-fitness-core\/blob\//.test(l.url))||null;}
export function evidenceFor(item,data){const related=(data?.items||[]).filter(i=>item.related_ids?.includes(i.id));const campaigns=related.filter(i=>i.kind==='campaign');const brief=canonicalBrief(item,data)||campaigns.map(i=>canonicalBrief(i,data)).find(Boolean)||null;const assetItems=[...related.filter(i=>i.kind==='asset'),...campaigns.flatMap(c=>(data?.items||[]).filter(i=>i.kind==='asset'&&c.related_ids.includes(i.id)))];const links=[...(item.links||[]),...assetItems.flatMap(i=>i.links||[])];const asset=links.find(l=>['asset','poster','image'].includes(l.role)&&/^https:\/\/(drive\.google\.com|docs\.google\.com)\//.test(l.url)&&!l.url.includes('/folders/'))||null;const folder=[...(item.links||[]),...campaigns.flatMap(c=>c.links||[])].find(l=>/^https:\/\/drive\.google\.com\/drive\/folders\//.test(l.url))||null;return {brief,asset,folder,campaigns,assets:assetItems};}
export function postDisplay(item,data){const evidence=evidenceFor(item,data);return {objective:item.fields.objective||'TBD — cieľ konkrétneho postu',title:item.title.replace(/(?:\s*\/\s*)?LF-(?:OUT|ASSET)-[A-Z0-9-]+/g,'').trim()||'Facebook výstup',status:publicationLabel(item).startsWith('Publikov')?'PUBLISHED_REPORTED':item.fields.approval==='APPROVED'&&item.fields.creative==='READY'?'READY':'DRAFT',...evidence};}
export function recentAdditions(data){return (data?.items||[]).filter(i=>(i.kind==='service'&&['IDEA','PROPOSED','PREPARING','PILOT'].includes(i.fields.lifecycle))||(i.kind==='idea'&&i.id.startsWith('LF-PROP-'))).sort((a,b)=>(dateValue(b.fields.added_at||b.fields.updated_at)||0)-(dateValue(a.fields.added_at||a.fields.updated_at)||0)).slice(0,5);}

export const itemTitle=item=>String(item.title).replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/[`*]/g,'');

export function taskCategory(item){return String(item.fields.category||'').trim()||'Kategória TBD';}
export function groupTasksByCategory(items){const groups=new Map();for(const item of items){const raw=taskCategory(item),category=raw&&!/^(TBD|MISSING|UNKNOWN)$/i.test(raw)?raw:'Kategória TBD';if(!groups.has(category))groups.set(category,[]);groups.get(category).push(item);}return [...groups].map(([category,items])=>({category,items}));}
export function nowAddedDate(item){const raw=String(item.fields.added_at||'').trim();const iso=raw.match(/^(\d{4})-(\d{2})-(\d{2})$/),sk=raw.match(/^(\d{1,2})\.\s*(\d{1,2})\.\s*(\d{4})$/);if(!iso&&!sk)return null;const [y,m,d]=iso?iso.slice(1).map(Number):[Number(sk[3]),Number(sk[2]),Number(sk[1])];const date=new Date(Date.UTC(y,m-1,d));return date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d?date.getTime():null;}
export function latestNowItems(data){return (data?.items||[]).filter(i=>i.kind==='task'&&nowAddedDate(i)!==null).sort((a,b)=>nowAddedDate(b)-nowAddedDate(a)).slice(0,5);}
